#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("NugetExplorer.Resource", IsApplication=true)]

namespace NugetExplorer
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_drawer = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int AddFeedDialog = 2131099648;
			
			// aapt resource value: 0x7f060006
			public const int AddFeedItem = 2131099654;
			
			// aapt resource value: 0x7f060004
			public const int ContentLayout = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int DrawNavigation = 2131099653;
			
			// aapt resource value: 0x7f060001
			public const int FeedName = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int FeedUri = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int MainLayout = 2131099651;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddFeedDialog = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int DrawListItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int ActionBarMenu = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040003
			public const int AddFeed = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int DrawerClose = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int DrawerOpen = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
